//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaPrecios
    {
        public int IdSegmento { get; set; }
        public int IdServicio { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
    
        public virtual Segmentos Segmentos { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
